generate_single_include:
    image: registry.gitlab.akhcheck.ru/artiom.khafizov/unittester
    tags:
        - common
    artifacts:
            paths:
                - single-include/UTest/UTest.hpp
            when: on_success
    script:
        - cmake -S . -B build && cd build && make
        - git config user.email "khafizov.ar@phystech.edu"
        - git config user.name "ci-bot"
        - git remote add gitlab_origin https://oauth2:glpat-hjgWg37saysQC3drx3pu@gitlab.akhcheck.ru:artiom.khafizov/unittester.git
        - cd ..
        - pwd
        - ls -a
        - git add single-include/
        - git commit -m "generated single-include by ci-bot"
        - git push gitlab_origin HEAD:main -o ci.skip # prevent triggering pipeline again
    