generate_single_include:
    image: python:3.9-slim-bullseye
    before_script:
        - apt-get --yes update && apt-get --yes install cmake && apt-get --yes install build-essential
    tags:
        - common
    artifacts:
            paths:
                - single-include/UTest/UTest.hpp
            when: on_success
    script:
        - cmake -S . -B build && build/make
