generate_single_include:
    image: python:3.9-slim-bullseye
    before_script:
        - sudo apt-get update && sudo apt-get install cmake
    tags:
        - saas-linux-medium-amd64
    script:
        - mkdir build && cmake -S . -B build && build/make
