generate_single_include:
    image: python:3.9-slim-bullseye
    before_script:
        - apt-get --yes update && apt-get --yes install cmake
    tags:
        - common
    script:
        - mkdir build && cmake -S . -B build && build/make
        - rm -r build
