#pragma once

#define UTEST_KEYWORD_UNDEFINED_RESULT "UNDEFINED"
#define UTEST_KEYWORD_TEST_START "RUN"
#define UTEST_KEYWORD_PASSED "OK"
#define UTEST_KEYWORD_FAILED "FAILED"
#define UTEST_KEYWORD_EXCEPTION_FAILED "FAILED EXCEPTION"
#define UTEST_KEYWORD_FATAL_FAILED "FATAL FAILED"
#define UTEST_KEYWORD_EXCEPTION_FATAL_FAILED "FATAL FAILED EXCEPTION"
