#pragma once

#define KEYWORD_PASSED "OK"
#define KEYWORD_FAILED "FAILED"
#define KEYWORD_EXCEPTION_FAILED "FAILED EXCEPTION"
#define KEYWORD_FATAL_FAILED "FATAL FAILED"
#define KEYWORD_EXCEPTION_FATAL_FAILED "FATAL FAILED EXCEPTION"
